# Generated by Django 5.1.4 on 2025-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(default=11, upload_to="brands/"),
            preserve_default=False,
        ),
    ]
