# Generated by Django 5.1.4 on 2025-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
