# Generated by Django 5.1.4 on 2025-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
