# Generated by Django 5.1.4 on 2025-06-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_id",
            field=models.CharField(default="default-id", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_customer_id",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
