# Generated by Django 5.1.4 on 2025-06-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_payment_stripe_checkout_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="stripe_checkout_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
