# Generated by Django 5.1.4 on 2025-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_remove_payment_stripe_checkout_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
