# Generated by Django 5.1.4 on 2025-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_payment_stripe_checkout_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("shipped", "shipped"),
                    ("Packed", "Packed"),
                    ("On the way", "On the way"),
                    ("Deliverd", "Deliverd "),
                    ("Cancelled", "Cancelled"),
                ],
                default="Placed",
                max_length=50,
            ),
        ),
    ]
