# Generated by Django 5.1.4 on 2025-06-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
